package testBase;

import java.io.FileReader;
import java.io.IOException;
import java.time.Duration;
import java.util.Properties;

import org.apache.logging.log4j.LogManager; //Log4j
import org.apache.logging.log4j.Logger; //Log4j


import org.apache.commons.lang3.RandomStringUtils;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Parameters;


public class BaseClass {

	public WebDriver driver;
	public Logger logger;
	public Properties p;
	
	@BeforeClass
	@Parameters({"os","browser"})
	public void setup(String os,String br) throws IOException
	{	
		//Loading config.properties files
		FileReader file = new FileReader("./src//test//resources//config.properties");
		p =new Properties();
		p.load(file);
		
		//logs
		logger=LogManager.getLogger(this.getClass());
		
		
		switch(br.toLowerCase())  //THis block which browser will launch based on testng.xml(msater.xml)file
		{
		case"chrome" : driver = new ChromeDriver(); break;
		case "edge" : driver = new EdgeDriver(); break;
		case "firefox" : driver = new FirefoxDriver(); break;
		default : System.out.println("Invalid Browser Name..."); return;
		}
		
		
		driver.manage().deleteAllCookies();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		
		driver.get(p.getProperty("appURL")); //reading URL from properties file
		driver.manage().window().maximize();
	}
	
	@AfterClass
	public void tearDown()
	{
		driver.close();
	}
	
	
	//Generating Random Inputs Methods
	public String randomString()
	{
		String generatedstring = RandomStringUtils.randomAlphanumeric(5);  //Predefined class in commons library we import it in dependency
		return generatedstring;	  										//5 Random Characters will be generated if we put 5
	}
	
	public String randomNumber()
	{
		String generatednumber = RandomStringUtils.randomNumeric(10);  // We have not used it but random mobile numbers can be generated by this
		return generatednumber;	  										
	}
	
	public String randomAlphanumeric ()  // For password generation
	{
		String generatedstring = RandomStringUtils.randomAlphanumeric(3);
		String generatednumber = RandomStringUtils.randomNumeric(3);
		return (generatedstring+"@"+generatednumber);	  										
	}
	
	
	
	
}














